require 'rails_helper'

feature 'visiting the homepage' do
  scenario 'a user can visit the homepage and request an entity analysis of a text file' do
    response = {"status" => "OK","usage" =>"By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html","url" => "","totalTransactions" => "2","language" => "english","text" => "Hello, my name is Nathanael Burt. I'm from Irvine, CA","entities" =>[{"type" => "Person","relevance" => "0.968376","sentiment" => {"type" => "negative", "score" => "-0.364699"},"count" => "1","text" => "Nathanael Burt"},{"type" => "City","relevance" => "0.390811","sentiment" => {"type" => "neutral"},"count" => "1","text" => "Irvine","disambiguated" =>{"subType" => ["AdministrativeDivision"],"name" => "Irvine, California","website" => "http://www.cityofirvine.org/","dbpedia" => "http://dbpedia.org/resource/Irvine,_California","freebase" => "http://rdf.freebase.com/ns/m.0d7k1z","geonames" => "http://sws.geonames.org/5359777/","yago" => "http://yago-knowledge.org/resource/Irvine,_California"}},{"type" => "StateOrCounty","relevance" => "0.292176","sentiment" => {"type" => "neutral"},"count" => "1","text" => "CA"}]}.to_json
    stub_request(:post, "http://access.alchemyapi.com/calls/text/TextGetRankedNamedEntities").
      to_return(body: response)
    visit '/'
    expect(page).to have_content 'Natural Language Processing'
    expect(page).to have_content 'Select the analysis type'
    select 'Entity Analysis'
    attach_file('alchemy_api[file]', './spec/support/test.txt')
    click_button 'Upload File'
    expect(page).to have_content 'Source Text'
    expect(page).to have_content "Hello, my name is Nathanael Burt. I'm from Irvine, CA"
    expect(page).to have_content 'Count: 1'
    expect(page).to have_content 'Text: Nathanael Burt'
    expect(page).to have_content 'Text: Irvine'
    expect(page).to have_content 'Text: CA'
    expect(page).to have_content 'Type: Person'
    expect(page).to have_content 'Type: City'
    expect(page).to have_content 'Type: State or County'
    expect(page).to have_content 'Relevance: 0.968376'
    expect(page).to have_content 'Sentiment Type: negative'
    expect(page).to have_content 'Sentiment Score: -0.364699'
    expect(page).to have_content 'Disambiguation Data:'
    expect(page).to have_content 'Name: Irvine, California'
    expect(page).to have_content 'Website: http://www.cityofirvine.org/'
    expect(page).to have_content 'DBpedia: http://dbpedia.org/resource/Irvine,_California'
    expect(page).to have_content 'Freebase: http://rdf.freebase.com/ns/m.0d7k1z'
    expect(page).to have_content 'Geonames: http://sws.geonames.org/5359777/'
    expect(page).to have_content 'Yago: http://yago-knowledge.org/resource/Irvine,_California'
    click_link 'Make another request'
    expect(page).to have_content 'Natural Language Processing'
  end

end