require 'rails_helper'

feature 'visiting the homepage' do
  scenario 'a user can visit the homepage and request an entity analysis of a text file' do
    response = {"status" => "OK", "usage" => "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use=> http=>//www.alchemyapi.com/company/terms.html", "url" => "", "totalTransactions" => "2", "language" => "english", "entities" => [{"type" => "Person", "relevance" => "0.33", "sentiment" => {"type" => "negative", "score" => "-0.364699"}, "count" => "1", "text" => "Nathanael Burt"}]}.to_json
    stub_request(:post, "http://access.alchemyapi.com/calls/text/TextGetRankedNamedEntities").
      to_return(body: response)
    visit '/'
    expect(page).to have_content 'Natural Language Processing'
    expect(page).to have_content 'Select the analysis type:'
    select 'Entity Analysis'
    attach_file('alchemy_api[file]', './spec/support/test.txt')
    click_button 'Upload File'
    expect(page).to have_content response
  end
end